### ISSUE TITLE
windows不能编译问题

### ISSUE THREAD

**Issue by degawong** [LostPeter/LostPeterVulkan#1]
你好，在知乎上看到你这个系列的入门文章，准备进场学习下，但是第一步就被卡到了，windows上无法编译，`error MSB4019: 未找到导入的项目“F:\Microsoft.Cpp.Default.props”`，我在这里提个建议，既然使用了cmake，可以直接使用cmake构建啊，windows脚本可能变数比较多，容易出现各种问题。
我的环境是`win10 / visual studio 2022`。
谢谢你的分享。

**Comment by LostPeter** [comment]
实际windows上就是使用cmake编译成了VS工程，工程的.sln都在Build的对应项目里面，这块只是直接跨过了生成的工程，调用脚本，使用msbuild直接把exe生成了出来。MacOS上也是如此。
我Windows/MacOS都习惯了只用VSCode来编辑代码，调试代码，这样不用麻烦的去Windows上还用VS，MacOS上去用XCode了，直接一个VSCode就完成了整个编辑，编译，生成，调试整个过程了，不用来回不同编辑器之间切换，这个还是很爽，效率很高的。

**Comment by LostPeter** [comment]
我Win10机器上也是用的VS2022的（Community版本），你可以在试下在命令行里能否调用msbuild编译vs工程，msbuild的那个路径需要加入到环境变量Path中去
